### ISSUE TITLE
English version

### ISSUE THREAD

**Issue by godlzr** [guovz/jekyll-pithy#1]
need english version

**Comment by jaylinwang** [comment]
thanks for your suggestion :smile:

**Comment by godlzr** [comment]
maybe I can help, I translated some pages and removed all your personal information. We can keep two branches.

**Comment by jaylinwang** [comment]
@godlzr 
Thank you for the translation. Could you please submit a PR to deveop branch and help me finish I18N.

A small suggestion,keep the coffeescript for the moment :smile: 

Thank you once again :clap:
