### ISSUE TITLE
模板github编译有问题?

### ISSUE THREAD

**Issue by tl3shi** [guovz/jekyll-pithy#13]
感谢提供这个模板~
我本地编译好的，和github编译的不一样。 github貌似translate的都失败了，但我看你的挺正常的呀， 奇怪~

[blog](http://www.tanglei.name/)

p.s 最近一直在折腾， 之前一直用[wordpress](http://wordpress.tanglei.name)，前几天折腾了[hexo](http://hexo.tanglei.name) 现在又换成jekyll。

代码高亮貌似不太好~
另外, 我用jekyll默认的twitter主题，然后用下面的配置 OK的， 见[这里](http://cv.tanglei.me/data%20structure/dsa-lighthouse.html)

```
markdown: redcarpet
redcarpet:
    extensions: ["fenced_code_blocks", "tables", "highlight", "strikethrough", "autolink"]
```

但在你的主题中， 若改成这样的配置，就编译不过了~ 说什么 字符集有问题~ 不太清楚具体什么原因。

**Comment by tl3shi** [comment]
你的gh-pages分支和master分支 样式等代码不一样~ 
master分支加了国际化(github不支持?) 然后你现在gh-pages分支那个多说也有问题，总弹窗。 
然后master分支在mobile下 菜单点击无效。

**Comment by jaylinwang** [comment]
github现在不再解析_plugins中的插件(主题里使用了catefory_generator.rb和i18n_filter.rb，所以主题中没有生效),如果有时间，还希望朋友帮忙改一下并提交pr :smile:  thanks

**Comment by tl3shi** [comment]
最近github更新jekyll版本，也highlight用了rouge.  我就本地编译好了，push编译好的html了，不让github帮忙编译了。哈哈~ 
还有一些优化空间, 比如 tags太多， 全部显示不太好， 我现在也就简单加了只显示50个。最好还是根据权重显示tag。 Liquid不太熟, 还有待学习。 
- [ ]  tag根据权重显示topN
- [x] 分页太多，中间显示 `...`
- [x] 移动端Bug, 点击菜单不弹框
