### ISSUE TITLE
你好，使用你的主题后，我的用户名.github.io 404错误，

### ISSUE THREAD

**Issue by timmy6** [guovz/jekyll-pithy#14]
你好，我是第一次在github上搭建博客，并且使用了你的主题，但是我commit到github上后，使用浏览器打开timmy6.github.io后，报404错误，并且，我的gmail邮箱，收到了“The page build failed with the following error:“邮件。我想请假一下，是什么原因？你能不能帮我看一下，感激不尽。我的github博客repo链接:[https://github.com/timmy6/timmy6.github.io]

**Comment by jaylinwang** [comment]
你需要commit至仓库的gh-pages分支哈 @timmy6
