### ISSUE TITLE
Can I create a branch ?

### ISSUE THREAD

**Issue by godlzr** [guovz/jekyll-pithy#7]

**Comment by jaylinwang** [comment]
Branch has been created，you can submit a PR

**Comment by godlzr** [comment]
Sweet, pushed a PR already, plz merge it.

**Comment by jaylinwang** [comment]
@godlzr Hi. thank you for your PR.base your PR. I finished i18n for this theme.you can setting your language with step:
1. create a yml name yourlocale.yml at _locales
2. config _config_yml locale: "yourlocale" 

 :smile:
