### ISSUE TITLE
主题如何使用？

### ISSUE THREAD

**Issue by wjpxjtu** [guovz/jekyll-pithy#9]
主题还是很不错的，很想用用，但是下载到本地之后，jekyll server无论如何都无法启动，一直都报各种各样的错误，博主能将这些都配置好么，谢谢~~

**Comment by jaylinwang** [comment]
@fucaobao 拷贝一份_config_default.yml为_.config.yml,然后配置为你自己的博客信息，运行jekyll serve

**Comment by wjpxjtu** [comment]
1. 谢谢博主，除了这个之外，还需要手动安装gem install i18n
2. 发现一个BUG，设置duoshuo_share为true时，会出现如图的bug
   ![bug](https://cloud.githubusercontent.com/assets/3930748/11375330/ad0f40a0-9315-11e5-8bc5-ce6143fcf0b1.png)

**Comment by jaylinwang** [comment]
是由于你未配置多说的short_name

**Comment by wjpxjtu** [comment]
@guovz 多谢帮助，终于搭建好了~~

**Comment by wjpxjtu** [comment]
关于i18n，本地测试是好的，但是发布到github上，似乎没有生效。
![1](https://cloud.githubusercontent.com/assets/3930748/11388213/92f614b0-936e-11e5-9a06-80cae7bd78ef.png)
![2](https://cloud.githubusercontent.com/assets/3930748/11388214/931f8e4e-936e-11e5-8505-baa09c4e898e.png)

**Comment by wjpxjtu** [comment]
我去掉了i18n，把相应的地方改成中文就可以了，谢谢~~

**Comment by jaylinwang** [comment]
@fucaobao 我在线上测试一下i18n。thanks :+1:

**Comment by wjpxjtu** [comment]
最终完全解决了这个问题，github为了安全，不解析_plugins中的插件了（对应这个主题里面的是catefory_generator.rb和i18n_filter.rb，都没有生效），一个解决方案就是，还是用原来的模版，然后jekyll server生成相应的文件，把_site文件夹中的文件发布到yourname.github.io之中

**Comment by jaylinwang** [comment]
这样的话就类似hexo了
